package io.openems.edge.ess.gridvolt.gridvolt1;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

@ObjectClassDefinition(//
		name = "GridVolt 1 ESS", //
		description = "OpenEMS implementation for GridVolt1 ESS")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "ess0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;
	
	@AttributeDefinition(name = "Inverter-1-ID", description = "ID of Inverter 1")
	String inverter_id() default "batteryInverter0";
	
	@AttributeDefinition(name = "Battery-ID", description = "ID of Battery")
	String battery_id() default "battery0";
	
	@AttributeDefinition(name = "ESS-Controller-Modbus-ID", description = "Modbus-ID for CCU")
	String modbus_id() default "modbus0";
	
	@AttributeDefinition(name = "ESS-Controller Modbus Unit-ID", description = "The Modbus Unit-ID of the ESS CCU.")
	int modbusUnitId() default 1;
	
	@AttributeDefinition(name = "Modbus target filter", description = "This is auto-generated by 'Modbus-ID'.")
	String Modbus_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "ESS GridVolt1 [{id}]";

}